baseURL = '/'
languageCode = 'en-us'
languageLang = "es"
title = 'PC Gamer Margarita'
theme = 'ananke'

[params]
# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
images = ["img/og-image.jpg"]
description = 'Todo en artículos de PC'
email = 'contact@pcgamermargarita.com'
phone = '+58 424-8813008'
address = 'Av. Llano Adentro, C.C. El Mercado La Isla, local PB L25, Porlamar 6301, Nueva Esparta, Venezuela'
maps_url = 'https://www.google.com/maps/place/El+Mercado+La+Isla/@10.9702,-63.8525,17z/data=!4m6!3m5!1s0x8c318ebaf32663ab:0xcac94b7762480813!8m2!3d10.9701044!4d-63.8525263!16s%2Fg%2F11dxsrhhx1?hl=es&entry=ttu&g_ep=EgoyMDI1MDYwNC4wIKXMDSoASAFQAw%3D%3D'

# Main site logo
site_logo = 'pcgamer_logo.jpg'

[params.social]
# facebook = 'https://facebook.com/pcgamermargarita'  # Deactivated - uncomment to enable
# twitter = 'https://twitter.com/pcgamermargarita'    # Deactivated - uncomment to enable
instagram = 'https://instagram.com/pcgamer.mgta'
youtube = 'https://youtube.com/pcgamermargarita'

[[params.footer_services]]
name = 'Gaming PCs'
url = '/gaming-pcs'

[[params.footer_services]]
name = 'Components'
url = '/components'

[[params.footer_services]]
name = 'Accessories'
url = '/accessories'

[[params.footer_services]]
name = 'Support'
url = '/support'